runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyBGhewxp9XdJWlow8e9ni2hQdHNeoXzHIE
  environment: "--prod"

handlers:
  - url: /
    secure: always
    static_files: dist/index.html
    upload: dist/.*
  - url: /(.*\.js)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/\1
    upload: dist/.*\.js
  - url: /(.*\.css)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/\1
    mime_type: text/css
    upload: dist/.*\.css
  - url: /.*
    secure: always
    static_files: dist/index.html
    upload: dist/.*

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
